"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import AppShell from "./AppShell";
import { loadStrategies, formatTime, money, percentage } from "../lib/data";
import type { AgentRun, StrategySummary } from "../lib/strategy-types";

export default function OverviewPage() {
  const [strategies, setStrategies] = useState<StrategySummary[]>([]); const [runs, setRuns] = useState<AgentRun[]>([]);
  useEffect(() => { loadStrategies().then(setStrategies).catch(() => undefined); fetch("/api/runs?limit=5", { cache: "no-store" }).then((r) => r.json()).then((d) => setRuns(d.runs || [])).catch(() => undefined); }, []);
  const strategyPath = (key: string) => key === "anomaly-binance" ? "/radar/anomaly" : key === "dualma4h-binance" ? "/radar/dualma" : "/radar/box-breakout";
  const strategyLabel = (key: string) => key === "anomaly-binance" ? "01 · ANOMALY" : key === "dualma4h-binance" ? "02 · CROSSOVER" : "03 · BOX BREAKOUT";
  return <AppShell title="总览" eyebrow="COMMAND CENTER"><div className="overview-hero"><div><span className="page-eyebrow">BINANCE AGENT OS · TRACK A</span><h2>让策略思考，<em>让你确认。</em></h2><p>三套独立策略共享一条可解释、可审计的 Paper 工作流。扫描什么、为什么选择、哪些已开仓，在这里都有证据。</p></div><div className="hero-orbit-mini"><b>MARKET</b><strong>→</strong><b>STRATEGY</b><strong>→</strong><b>RISK GATE</b></div></div><div className="kpi-grid"><div><span>策略</span><strong>03</strong><small>A档 + 双均线 + 箱体</small></div><div><span>实时数据</span><strong>Binance</strong><small>公开行情</small></div><div><span>Paper 边界</span><strong>LOCKED</strong><small>broadcast=false</small></div><div><span>运行记录</span><strong>{runs.length}</strong><small>最近 5 次</small></div></div><section className="overview-section"><div className="section-title"><div><span className="table-kicker">STRATEGY WORKSPACES</span><h2>三套策略，三个判断体系</h2></div></div><div className="strategy-overview-grid">{strategies.map((strategy) => <Link key={strategy.key} className="strategy-overview-link" href={strategyPath(strategy.key)}><span className="strategy-tag">{strategyLabel(strategy.key)}</span><h3>{strategy.name}</h3><p>{strategy.desc}</p><div><strong>{money(strategy.summary.equity)}</strong><span className={strategy.summary.totalReturnPct >= 0 ? "positive" : "negative"}>{percentage(strategy.summary.totalReturnPct)} total</span></div><b>进入工作台 →</b></Link>)}</div></section><section className="overview-section"><div className="section-title"><div><span className="table-kicker">LATEST AGENT RUNS</span><h2>最近运行</h2></div><Link className="inline-link" href="/runs">查看全部 →</Link></div>{runs.length ? <div className="run-preview">{runs.slice(0, 4).map((run) => <div key={run.run_id}><span className="status-chip live">完成</span><strong>{run.strategy === "anomaly-binance" ? "A档异动扫描" : run.strategy === "dualma4h-binance" ? "双均线 4H" : "30m 箱体突破"}</strong><span>{run.scanned_count} 扫描 · {run.candidate_count} 候选 · {formatTime(run.completed_at)}</span></div>)}</div> : <div className="empty-state">暂无 Agent Tool Layer 运行记录；策略扫描和 Paper 交易由后台自动运行。</div>}</section></AppShell>;
}
